# Generated by Django 2.2.1 on 2019-05-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('buyer', '0001_initial'),
        ('shipping', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='shipping.Country'),
        ),
        migrations.AddField(
            model_name='shippaddress',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer'),
        ),
        migrations.AddField(
            model_name='myorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer'),
        ),
        migrations.AddField(
            model_name='myorder',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='billing.OrderItem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.MyOrder'),
        ),
        migrations.AddField(
            model_name='dispatched',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.MyOrder'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='billing.CartItem'),
        ),
    ]
