# Generated by Django 2.2.1 on 2019-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190506_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='billing.CartItem'),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='items',
            field=models.ManyToManyField(to='billing.OrderItem'),
        ),
    ]
