# Generated by Django 2.2.1 on 2019-05-06 10:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('name', models.CharField(max_length=500, verbose_name='Heading')),
                ('date', models.DateField(verbose_name='Date')),
                ('specification', ckeditor.fields.RichTextField(verbose_name='spacification for a product')),
                ('product_no', models.IntegerField()),
                ('Note', models.TextField(max_length=500, verbose_name='Any Notes')),
                ('Features', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='features of products')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='working of this Products video url ')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('dummy_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0, verbose_name='Weight in grams')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta Keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('count', models.IntegerField()),
                ('is_slide', models.BooleanField(default=False, verbose_name='Show in slider ?')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/blog', verbose_name='Image (828px X 363px)')),
                ('tax_included', models.BooleanField(default=True)),
                ('service_tax', models.FloatField(default=0.0, verbose_name='Service tax(mention in  percetage)')),
                ('sales_tax', models.FloatField(default=0.0, verbose_name='Sales tax(mention in  percetage)')),
                ('vat', models.FloatField(default=0.0, verbose_name='Value Added Tax(mention in  percetage)')),
                ('cess', models.FloatField(default=0.0, verbose_name='Cess Tax(mention in percetage)')),
                ('cst', models.FloatField(default=0.0, verbose_name='Central Sales Tax(mention in  percetage)')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active or Not')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('feauterd_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/category', verbose_name='image(height:346px,width:895px)')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_menu', models.BooleanField(default=False, verbose_name='Is Menu')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500, verbose_name='Heading')),
                ('date', models.DateField(verbose_name='Published Date')),
                ('author', models.CharField(max_length=500, verbose_name='name')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/blog', verbose_name='Blog Image (828px X 363px)')),
                ('discription', ckeditor.fields.RichTextField(verbose_name='discription about the product')),
                ('tutorial', models.TextField(blank=True, null=True, verbose_name='How to use')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification')),
                ('active', models.BooleanField(default=True, verbose_name='resource Active or Not')),
                ('is_featured', models.BooleanField(default=False, verbose_name='resource featured or Not (only one)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='product.Products')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Image Name')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/blog', verbose_name='Blog Image (828px X 363px)')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rgallery', to='product.Resources')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=mptt.fields.TreeManyToManyField(related_name='products', to='product.Section'),
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Image Name')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/blog', verbose_name='Blog Image (828px X 363px)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.Products')),
            ],
        ),
    ]
