# Generated by Django 2.2.1 on 2019-07-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon class name(eg: flaticon-dress-1)'),
        ),
    ]
