# Generated by Django 2.2.1 on 2019-07-18 15:54

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_section_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/products', verbose_name='Image (220px X 270px)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_no',
            field=models.CharField(max_length=50, verbose_name='prodcut no'),
        ),
    ]
