# Generated by Django 2.2.1 on 2019-05-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='is_verifed',
            new_name='is_verified',
        ),
    ]
