# Generated by Django 2.2.1 on 2019-05-09 06:58

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=50, verbose_name='Owner Name')),
                ('site_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/category', verbose_name='Logo(height:25px,width:33px)')),
                ('faviicon', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/category', verbose_name='Favicon(height:16px,width:19px)')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('copyright', models.CharField(max_length=50, verbose_name='Copy right')),
            ],
            options={
                'verbose_name': 'SiteCOnfig',
                'verbose_name_plural': 'SiteCOnfigs',
            },
        ),
    ]
