# Generated by Django 2.2.1 on 2019-05-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='faviicon',
            new_name='fav_icon',
        ),
    ]
