# Generated by Django 2.2.1 on 2019-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190509_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
