# Generated by Django 2.2.1 on 2019-05-10 07:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_siteconfig_meta_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'SiteConfig', 'verbose_name_plural': 'SiteConfigs'},
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='fav_icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/site', verbose_name='Favicon(height:16px,width:19px)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/site', verbose_name='Logo(height:25px,width:33px)'),
        ),
    ]
