# Generated by Django 2.2.1 on 2019-05-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country name')),
                ('fuel_surcharge', models.FloatField(blank=True, default=0.0, null=True)),
                ('service_tax', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Zone Name')),
                ('zone_cat', models.CharField(choices=[('D', 'Domestic'), ('I', 'International')], max_length=2, verbose_name='Zone Category')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='shipping.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.FloatField(verbose_name='Weight From (gm)')),
                ('value2', models.FloatField(verbose_name='Weight To (gm)')),
                ('price', models.FloatField(default=0.0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rate', to='shipping.Zone', verbose_name='Zone')),
            ],
        ),
    ]
